[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--no-audit --fund=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"
